server:
  port: 8081
spring:
  thymeleaf:
    cache: false
    mode: HTML5
  servlet:
    multipart:
      max-file-size: 5MB
dubbo:
  application:
    name: shop_back
  registry:
    address: zookeeper://192.168.110.128:2181
  consumer:
    check: false
    timeout: 1000
fdfs:
  so-timeout: 1500
  connect-timeout: 600
  pool:
    jmx-enabled: false
  thumb-image:
    width: 100
    height: 100
  tracker-list:
    - 192.168.110.128:22122
image:
  path: http://192.168.110.128/